# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a613f69c301e061cbb0bcde60c54946dc9782b13196f1d9910bb7b66a8f06e3104cb0f193322273afe14067a3ef986e4e4869c4dddf8c747395de1a3dc884430

test:
  secret_key_base: 4a49dab50c0132006a6d6de5efc1983765a614eccd7619f99423e2123adf5143ff7380e360943b6f104380e66c0cb52928d1c7b631669f75ff65d070136943e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
